{% set name = "modshim" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/modshim-{{ version }}.tar.gz
  sha256: c6b5173be63b436163274fe19747edf4021970d96f38ab22f3cd6c24c4e6dca1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - modshim
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/joouha/modshim
  dev_url: https://github.com/joouha/modshim
  summary: Override and customize Python packages without touching their code.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - apcamargo
