{% set name = "modshim" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/modshim-{{ version }}.tar.gz
  sha256: f6cbcf3b539bd8b3d3e4decb6048a7b135e3fba74a60833430353933ee10ef6c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - modshim
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/joouha/modshim
  dev_url: https://github.com/joouha/modshim
  summary: Override and customize Python packages without touching their code.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - apcamargo
